extends RefCounted
class_name Config

enum Phase { WANDER, ALIGN, REPEL }
enum RenderStyle { POINTS, CIRCLES, VELOCITY_LINES }
enum ZoneType { REPULSE, ATTRACT }

const TICKS_PER_SECOND = 24
const TICK_DT = 1.0 / float(TICKS_PER_SECOND)
const DEFAULT_AGENT_COUNT = 1000
const DEFAULT_SEED = 12345
const RESEED_ON_RESTART = true
const SHOW_DEBUG_UI = true
const ALLOW_PAUSE = true
const DEBUG_PRINT_SEED = true

const DENSITY_THRESHOLD_LOW = 5.0
const DENSITY_THRESHOLD_HIGH = 7.0
const NEIGHBOR_RADIUS = 28.0
const GRID_CELL_SIZE = NEIGHBOR_RADIUS
const DENSITY_SCALE = 2600.0
const FORCE_WANDER = 8.5
const FORCE_ALIGN = 30.0
const FORCE_REPEL = 36.0
const FORCE_COHESION = 12.0
const FORCE_SEPARATION = 18.0
const WANDER_ALIGN_FACTOR = 0.3
const WANDER_COHESION_FACTOR = 0.15
const ALIGN_SEPARATION_FACTOR = 0.4
const ALIGN_TRIANGLE_LATTICE_FACTOR = 0.9
const TRIANGLE_LATTICE_DISTANCE = 20.0
const ALIGN_NOISE_FACTOR = 0.15
const REPEL_NOISE_FACTOR = 0.8
const NOISE_MAGNITUDE = 6.0
const MAX_SPEED = 120.0
const MIN_SPEED = 34.0
const DAMPING = 0.998

const SPAWN_PADDING = 16.0
const SPAWN_SPEED_MIN = 34.0
const SPAWN_SPEED_MAX = 100.0

const RENDER_STYLE = RenderStyle.CIRCLES
const RENDER_POINT_RADIUS = 3.0
const RENDER_CIRCLE_RADIUS = 5.0
const RENDER_VELOCITY_LINE_SCALE = 0.35
const TRAILS_ENABLED = true
const TRAIL_FADE_COLOR = Color(0.0, 0.0, 0.0, 0.06)
const COLOR_DEFAULT = Color(0.9, 0.9, 0.9, 1.0)
const COLOR_WANDER = Color(0.9, 0.9, 0.9, 1.0)
const COLOR_ALIGN = Color(0.3, 0.8, 1.0, 1.0)
const COLOR_REPEL = Color(1.0, 0.3, 0.3, 1.0)

const ZONE_RADIUS = 100.0
const ZONE_RADIUS_MAX = 180.0
const ZONE_DURATION = 15.0
const ZONE_RADIUS_GROWTH = 6.0
const ZONE_GROW_PER_SECOND = 28.0
const ZONE_FORCE_REPEL = 220.0
const ZONE_FORCE_ATTRACT = 200.0
const ZONE_FALLOFF_POWER = 1.0
const ZONE_COLOR_REPEL = Color(1.0, 0.45, 0.45, 0.18)
const ZONE_COLOR_ATTRACT = Color(0.45, 0.75, 1.0, 0.18)
const ZONE_GLOW_OUTER_ALPHA = 0.08

const HOVER_PICK_RADIUS = 10.0
