extends RefCounted
class_name Config

enum Phase { WANDER, ALIGN, REPEL }
enum RenderStyle { POINTS, CIRCLES, VELOCITY_LINES }
enum ZoneType { REPULSE, ATTRACT }

const TICKS_PER_SECOND = 24
const TICK_DT = 1.0 / float(TICKS_PER_SECOND)
const DEFAULT_AGENT_COUNT = 1000
const DEFAULT_SEED = 12345
const RESEED_ON_RESTART = true
const SHOW_DEBUG_UI = true
const ALLOW_PAUSE = true
const DEBUG_PRINT_SEED = true
const PERF_PROFILING_ENABLED = false
const PERF_PRINT_EVERY_TICKS = 30
const PERF_PRINT_EVERY_FRAMES = 30

const DENSITY_THRESHOLD_LOW = 5.0
const DENSITY_THRESHOLD_HIGH = 7.6
const DENSITY_HYSTERESIS = 0.8
const NEIGHBOR_RADIUS = 34.0
const GRID_CELL_SIZE = NEIGHBOR_RADIUS
const DENSITY_SCALE = 2600.0
const PHASE_MIN_DURATION = 1.4
const MEMORY_GRID_SIZE = Vector2i(96, 96)
const MEMORY_MAX = 6.0
const MEMORY_DEPOSIT_PER_UNIT = 0.03
const MEMORY_DECAY_RATE = 0.6
const MEMORY_DIFFUSION = 0.08
const MEMORY_FORCE_STRENGTH = 18.0
const MEMORY_DEPOSIT_RADIUS = 0
const MEMORY_ENABLED_DEFAULT = false
const MEMORY_UPDATE_EVERY_TICKS = 2
const MEMORY_STRENGTH_WANDER = 0.6
const MEMORY_STRENGTH_ALIGN = 0.25
const MEMORY_STRENGTH_REPEL = -0.4
const DENSITY_GRID_SIZE = Vector2i(128, 128)
const DENSITY_KERNEL_RADIUS = 2
const DENSITY_KERNEL_FALLOFF = 0.6
const DENSITY_GLOW_PERCENTILE = 0.95
const DENSITY_GLOW_ALPHA_MIN = 0.12
const DENSITY_GLOW_ALPHA_MAX = 0.35
const DENSITY_UPDATE_EVERY_TICKS = 2
const FORCE_WANDER = 8.5
const FORCE_ALIGN = 38.0
const FORCE_REPEL = 28.0
const FORCE_COHESION = 12.0
const FORCE_SEPARATION = 24.0
const SEPARATION_BOOST = 1.25
const MIN_SEPARATION_RATIO = 0.2
const DENSITY_SEPARATION_BOOST = 2.0
const DENSITY_COHESION_DAMP = 0.6
const WANDER_ALIGN_FACTOR = 0.6
const WANDER_COHESION_FACTOR = 0.35
const ALIGN_SEPARATION_FACTOR = 0.5
const ALIGN_TRIANGLE_LATTICE_FACTOR = 0.9
const TRIANGLE_LATTICE_DISTANCE = 20.0
const ALIGN_NOISE_FACTOR = 0.05
const REPEL_NOISE_FACTOR = 0.5
const NOISE_MAGNITUDE = 4.0
const MAX_SPEED = 120.0
const MIN_SPEED = 34.0
const DAMPING = 0.998
const MAX_TURN_RATE = 2.6
const FORCE_FORWARD = 6.0

const SPAWN_PADDING = 16.0
const SPAWN_SPEED_MIN = 34.0
const SPAWN_SPEED_MAX = 100.0

const RENDER_STYLE = RenderStyle.CIRCLES
const RENDER_POINT_RADIUS = 3.0
const RENDER_CIRCLE_RADIUS = 5.0
const RENDER_VELOCITY_LINE_SCALE = 0.35
const AGENT_BODY_RADIUS = max(RENDER_POINT_RADIUS, RENDER_CIRCLE_RADIUS)
const MIN_SEPARATION_DISTANCE = AGENT_BODY_RADIUS * 3.6
const CLOSE_SEPARATION_MULT = 5.0
const TRAILS_ENABLED = true
const TRAIL_FADE_COLOR = Color(0.0, 0.0, 0.0, 0.06)
const COLOR_DEFAULT = Color(0.9, 0.9, 0.9, 1.0)
const COLOR_WANDER = Color(0.9, 0.9, 0.9, 1.0)
const COLOR_ALIGN = Color(0.3, 0.8, 1.0, 1.0)
const COLOR_REPEL = Color(1.0, 0.3, 0.3, 1.0)
const TRAIL_DENSITY_INTENSITY = 0.65

const ZONE_RADIUS = 100.0
const ZONE_RADIUS_MAX = 180.0
const ZONE_DURATION = 15.0
const ZONE_RADIUS_GROWTH = 6.0
const ZONE_GROW_PER_SECOND = 28.0
const ZONE_FORCE_REPEL = 220.0
const ZONE_FORCE_ATTRACT = 200.0
const ZONE_FALLOFF_POWER = 2.0
const ZONE_FORCE_CAP = 260.0
const ZONE_COLOR_REPEL = Color(1.0, 0.45, 0.45, 0.18)
const ZONE_COLOR_ATTRACT = Color(0.45, 0.75, 1.0, 0.18)
const ZONE_GLOW_OUTER_ALPHA = 0.08
const ZONE_MEMORY_DEPOSIT_SCALE = 0.02

const HOVER_PICK_RADIUS = 10.0
